### ISSUE TITLE
To-Do Item Updates make To-Do Entity temporarily unavailable

### ISSUE THREAD

**Issue by VidFerris** [Hantick/ticktick-home-assistant#25]
I have a Script which I am using to find and iterate through overdue tasks, which I want to then mark as complete and sync their status back to TickTick. I'm doing this by calling the todo.update_item action within the script. However, after each todo.update_item call, the todo entity immediately becomes unavailable while (I think) the list re-synchronises with the TickTick cloud. As a consequence, I have to add a wait into the loop after each item marked as complete for the todo entity to become available again.

It may be nicer if, rather than a re-sync immediately upon a single item being updated, cloud syncing waited over a period of time (e.g. 5 to 10 seconds) where additional [_post](https://github.com/Hantick/ticktick-home-assistant/blob/115615bde2192b25f5ca4ee2e4feff643fdba28a/custom_components/ticktick/ticktick_api_python/ticktick_api.py#L93) calls accumulate in a buffer. Then, rather than each _post call triggering a full re-sync, multiple _post calls can be queued and submitted to the TickTick cloud before re-syncing.

Alternatively, making sure the existing todo entity persists and remains available during the synchronisation process would be good also, though without the update queuing it may still be making a lot of needless synchronisation calls.

In case it helps diagnose the issue, the script YAML and a relevant timeline trace is included below; you can see how while the first item is checked off immediately, the script needs to wait one minute for a full sync to complete before being able to mark off the next item.

All that said - thanks again for making this integration!

![Image](https://github.com/user-attachments/assets/07aba8d9-a4d7-452b-85f5-9fd47c7f3966)

```
alias: Tick Off ALL Overdue Tasks in list
description: >
  Completes all tasks in the given to-do list that are overdue (i.e., due before
  today and not yet completed).
mode: parallel
fields:
  todo_entity:
    name: To-do Entity
    description: The to-do list to operate on (e.g., todo.morning).
    required: true
    example: todo.morning
    selector:
      entity:
        domain: todo
sequence:
  - alias: Fetch tasks from to-do list
    data:
      entity_id: "{{ todo_entity }}"
    response_variable: todo_items_response
    action: todo.get_items
  - alias: Filter overdue tasks
    variables:
      all_tasks: "{{ todo_items_response[todo_entity]['items'] }}"
      overdue_tasks: |
        {% set tasks = namespace(items=[]) %} {% for t in all_tasks %}
          {% if t.status != 'completed'
             and t.due is defined
             and t.due not in ['', None]
             and as_local(as_datetime(t.due)).date() < now().date() %}
            {% set tasks.items = tasks.items + [t] %}
          {% endif %}
        {% endfor %} {{ tasks.items }}
  - alias: Loop through overdue tasks and complete them
    repeat:
      for_each: "{{ overdue_tasks }}"
      sequence:
        - alias: If list unavailable, wait until it is available
          if:
            - condition: template
              value_template: "{{ states(todo_entity) == 'unavailable' }}"
          then:
            - wait_for_trigger:
                - value_template: "{{ states(todo_entity) != 'unavailable' }}"
                  trigger: template
              timeout:
                minutes: 5
              continue_on_timeout: true
              alias: Wait up to 5 mins
        - alias: Ensure list is available before updating
          if:
            - condition: template
              value_template: "{{ states(todo_entity) != 'unavailable' }}"
          then:
            - alias: Mark task as completed
              data:
                item: "{{ repeat.item.uid }}"
                status: completed
              target:
                entity_id: "{{ todo_entity }}"
              action: todo.update_item
            - alias: Logbook entry
              data:
                name: Tick Off Overdue Tasks
                message: Marked overdue task '{{ repeat.item.summary }}' as completed.
                domain: script
              action: logbook.log
          else:
            - alias: Log failure due to unavailability
              data:
                name: Tick Off Overdue Tasks
                message: >
                  Could not mark '{{ repeat.item.summary }}' as completed
                  because {{ todo_entity }} was unavailable.
                domain: script
              action: logbook.log

```
